---
# Basics
- hosts: all
  roles:
    - base
    - ruby
    - vim

# DB
- hosts: all
  roles:
    - postgresql

# Servers
- hosts: all
  roles:
    - nginx
    - puma

- hosts: all
  user: vagrant
  tasks:
    - name: Ramove Apache2
      apt: name={{ item }} state=absent purge=yes force=yes
      with_items:
        - apache2
        - apache2-utils

    # Install PhantomJS
    - name: Download PhantomJS
      get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 dest=/tmp/ validate_certs=no sha256sum=a1d9628118e270f26c4ddd1d7f3502a93b48ede334b8585d11c1c3ae7bc7163a

    - name: Unarchive PhantomJS
      unarchive: src=/tmp/phantomjs-1.9.8-linux-x86_64.tar.bz2 dest=/usr/local/bin group=root owner=root mode=0755 copy=no
      sudo: yes
