---
rails_env:    development
target:       virtualbox
path:         /vagrant

rails_version:  4
ruby_install:   rbenv
ruby_version:   2.1.2


user_name:      '{{ "vagrant" if target == "virtualbox" else app_name }}'
group_name:     '{{ user_name }}'
user_home_path: '/home/{{ user_name }}'

postgresql_db_name:     site_development
postgresql_db_user:     vagrant
postgresql_db_password: vagrant
postgresql_extensions:
  - hstore
  - postgis

app_path: '{{ path if target == "virtualbox" else "{{ path }}/current" }}'
app_public_path: "{{ app_path }}/public"
app_config_path: "{{ app_path }}/config"
app_temp_path: "{{ app_path }}/tmp"
app_logs_path: "{{ app_path }}/log"

ruby_user_name: '{{ "root" if ruby_install == "package" else user_name }}'

server_type:  nginx_puma
server_name:  localhost
ssl_certificate_path:     /etc/nginx/ssl/{{ server_name }}.crt
ssl_certificate_key_path: /etc/nginx/ssl/{{ server_name }}.key

puma_bind_path: "unix://{{ app_temp_path }}/sockets/puma.{{ rails_env }}.sock"
puma_config_path: "{{ app_config_path }}/puma.{{ rails_env }}.rb"
puma_pidfile_path: "{{ app_temp_path }}/pids/puma.{{ rails_env }}.pid"
puma_stderr_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.err.log"
puma_stdout_redirect_path: "{{ app_logs_path }}/puma.{{ rails_env }}.log"

